name: Docker Build and Push

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

    - name: Set an environment variable
      shell: bash
      run: echo "APP_NAME=an-sql-sync" >> $GITHUB_ENV && echo "ORG_NAME=dsa-sf" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ env.ORG_NAME }}/${{env.APP_NAME}}:${{ env.BRANCH_NAME }}

    - name: Build and push latest tag
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ env.ORG_NAME }}/${{env.APP_NAME}}:latest
